name: rayspace3d_preprocess_linux
channels:
  - conda-forge
  - nvidia
dependencies:
  # Core
  - python=3.11
  - cmake>=3.25
  - make
  - pkg-config
  
  # Compilers
  - gcc_linux-64=11.*
  - gxx_linux-64=11.*
  
  # CUDA
  - cuda-toolkit=12.8
  
  # C++ Libraries
  - cgal>=6.0
  - libgomp
  - tinyobjloader
  - boost-cpp
  - eigen
