name: rayspace3d_preprocess
channels:
  - conda-forge
  - nvidia
dependencies:
  # Core
  - python=3.11
  - cmake>=3.25
  - ninja
  
  # CUDA
  - cuda-toolkit=12.8
  
  # C++ Libraries
  - cgal>=6.0
  - tinyobjloader
  - eigen
